const GET_SLIDERS = 'GET_SLIDERS';
const GET_DATALIST = 'GET_DATALIST';
const GET_CHOOSE = 'GET_CHOOSE';
const GET_GROOM = 'GET_GROOM';
const GET_LIST1 = 'GRT_LIST1'
const GET_LIST2 = 'GRT_LIST2'
const GET_LIST3 = 'GRT_LIST3'



export {
    GET_SLIDERS,
    GET_DATALIST,
    GET_CHOOSE,
    GET_GROOM,
    GET_LIST1,
    GET_LIST2,
    GET_LIST3,
}