const GET_SLIDERS = 'GET_SLIDERS';
const GET_DATALIST = 'GET_DATALIST';
const GET_CHOOSE = 'GET_CHOOSE';
const GET_GROOM = 'GET_GROOM';



export {
    GET_SLIDERS,
    GET_DATALIST,
    GET_CHOOSE,
    GET_GROOM
}