const GET_SLIDERS = 'GET_SLIDERS';
const GET_DATALIST = 'GET_DATALIST';
const GET_CURRENTLIST='GET_CURRENTLIST';
const GET_PRDDETAIL = 'GET_PRDDETAIL';
const GET_CHOOSE = 'GET_CHOOSE';
const GET_CHANGETYPE = 'GET_CHANGETYPE';

export {
    GET_SLIDERS,
    GET_DATALIST,
    GET_CURRENTLIST,
    GET_PRDDETAIL,
    GET_CHOOSE,
    GET_CHANGETYPE
}